root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = ["run", "-p", "9090"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 0
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "frontend",
    "test_projects",
    "mailpit",
    "deployment",
]
exclude_file = []
exclude_regex = ["_test.go", ".sqlite"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true
post_cmd = ["lsof -i :9090 | grep main | awk '{print $2}' | xargs kill"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
