project_name: sloth

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: .
    binary: sloth
    ldflags:
      - |
        -s -w
        -X github.com/devs-group/sloth/config.GithubClientKey={{ .Env.GH_CLIENT_KEY }}
        -X github.com/devs-group/sloth/config.GithubSecret={{ .Env.GH_SECRET }}
        -X github.com/devs-group/sloth/config.GithubAuthCallbackURL={{ .Env.GH_AUTH_CALLBACK }}
        -X github.com/devs-group/sloth/config.SessionSecret={{ .Env.SESSION_SECRET }}
        -X github.com/devs-group/sloth/config.Host={{ .Env.HOST }}
        -X github.com/devs-group/sloth/config.FrontendHost={{ .Env.FRONTEND_HOST }}
        -X github.com/devs-group/sloth/config.ProjectsDir={{ .Env.PROJECTS_DIR }}
        -X github.com/devs-group/sloth/config.Version={{ .Env.VERSION }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      # - arm64
      # - arm
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^frontend:"
