version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deployment/Containerfile
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "9090:9090"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deployment/traefik.toml:/etc/traefik/traefik.toml
      - ./deployment/entrypoint.sh:/entrypoint.sh
      - ./:/go/src/app
      - /go/src/app/bin # prevent to override bin folder inside container
