####################
# Base
####################
FROM docker:dind as base

RUN apk --no-cache add curl tar

# Install Go
ENV GOLANG_VERSION 1.22.2
RUN curl -L -o /tmp/go.tar.gz https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf /tmp/go.tar.gz \
    && rm -f /tmp/go.tar.gz
ENV PATH $PATH:/usr/local/go/bin
ENV GOPATH /go
ENV PATH $PATH:/usr/local/go/bin:$GOPATH/bin

# Install Node.js
ENV NODE_VERSION 20.6.1
RUN apk --no-cache add nodejs npm \
    && npm install -g "node@${NODE_VERSION}"
ENV NODE_PATH /usr/local/lib/node_modules
ENV PATH $NODE_PATH:$PATH

####################
# Source
####################
FROM base as source

WORKDIR /go/src/app
COPY . .

####################
# Build
####################
FROM source as build

WORKDIR /go/src/app

RUN npm --prefix ./frontend ci
RUN npm --prefix ./frontend run generate:prod

RUN go mod download
RUN go build -tags prod -o /go/src/app/bin/sloth

####################
# Run
####################
FROM build as run

WORKDIR /go/src/app

CMD ["/go/src/app/bin/sloth", "run", "-p", "9090"]
