[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[api]
  insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[log]
  level = "INFO"

[dashboard]
  [dashboard.auth]
    [dashboard.auth.basic]
      users = ["admin:admin123"]