name: Make a new release
on:
  pull_request:
    paths:
      - '.github/**'
      - 'frontend/**'
      - 'backend/**'
  push:
    branches:
      - main
    tags:
      - "*"

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/sloth:latest

jobs:
  lint-nuxt:
    name: Lint Nuxt
    runs-on: ubuntu-latest
    container:
      image: node:20.6.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run Nuxt lint
        working-directory: frontend
        run: npm run lint .

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    container:
      image: golang:1.21.1-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: .
        run: go get

      - name: Run Backend Tests
        working-directory: .
        run: go test ./...

  build_docker:
    runs-on: ubuntu-latest
    needs: [lint-nuxt, test-backend]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/Containerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

  build:
    runs-on: ubuntu-latest
    needs: [lint-nuxt, test-backend]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.1
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.1"
      - name: Install node dependencies
        run: cd frontend && npm install --ci
      - name: Export env vars
        run: |
          echo "GH_CLIENT_KEY=${{ secrets.GH_CLIENT_KEY }}" >> $GITHUB_ENV
          echo "GH_SECRET=${{ secrets.GH_SECRET }}" >> $GITHUB_ENV
          echo "GH_AUTH_CALLBACK=${{ secrets.GH_AUTH_CALLBACK }}" >> $GITHUB_ENV
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> $GITHUB_ENV
          echo "HOST=${{ env.HOST }}" >> $GITHUB_ENV
          echo "FRONTEND_HOST=${{ env.FRONTEND_HOST }}" >> $GITHUB_ENV
          echo "PROJECTS_DIR=./projects" >> $GITHUB_ENV
          echo "VERSION=${{ github.ref }}" >> $GITHUB_ENV
      - name: Build node
        run: |
          cd frontend && npm run generate:prod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
