name: Make a new release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.1
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.1"
      - name: Install node dependencies
        run: cd frontend && npm install --ci
      - name: Build node
        run: |
          cd frontend && npm run generate
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_CLIENT_KEY: ${{ secrets.GH_CLIENT_KEY }}
          GH_SECRET: ${{ secrets.GH_SECRET }}
          GH_AUTH_CALLBACK: ${{ secrets.GH_AUTH_CALLBACK }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          HOST: ${{ secrets.HOST }}
